# Generated by Django 4.1.5 on 2023-01-25 22:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Location type',
                'verbose_name_plural': 'Location types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.00')), django.core.validators.MaxValueValidator(Decimal('90.00'))], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.00')), django.core.validators.MaxValueValidator(Decimal('180.00'))], verbose_name='Longitude')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.locationtype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
