# Generated by Django 4.1.5 on 2023-03-06 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0004_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='favourite',
            field=models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
