# Generated by Django 4.1.5 on 2023-03-09 11:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0005_location_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='Label')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.00')), django.core.validators.MaxValueValidator(Decimal('90.00'))], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.00')), django.core.validators.MaxValueValidator(Decimal('180.00'))], verbose_name='Longitude')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='Icon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Custom pin',
                'verbose_name_plural': 'Custom pins',
            },
        ),
    ]
