# Generated by Django 4.1.5 on 2023-03-09 13:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_custompin_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompin',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('-90.00')), django.core.validators.MaxValueValidator(Decimal('90.00'))], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='custompin',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('-180.00')), django.core.validators.MaxValueValidator(Decimal('180.00'))], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('-90.00')), django.core.validators.MaxValueValidator(Decimal('90.00'))], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('-180.00')), django.core.validators.MaxValueValidator(Decimal('180.00'))], verbose_name='Longitude'),
        ),
    ]
